### ISSUE TITLE
V1 scope

### ISSUE THREAD

**Issue by cammellos** [status-im/status-protocol-go#8]
This issues is an epic for  v1 scope, leaving old comment for posterity, but to have an up-to-date view please see: https://github.com/orgs/status-im/projects/54 , as that's the only place where we will keep things up to date.

### Outdated

- [x] Integrate status-protocol-go with status-react: #2 5d
- [x] Move chats to status-protocol-go #3 3d
- [x] Move messages to status-go #5 5d
- [x] Move contacts to status-go #10 3d
- [x] Move accounts to status-go #11 5d
- [x] Integrate data-sync #7 5d
- [x] Disable discovery topic #12 1d 
- [x] Add persistence to mvds #15 1d

#### Bugfixes

#9 1d

This is the minimum that we have to do, potentially new tasks might come up given that the plan is also to get rid of realm.

The main goal is to move all those parts that would involve a data breaking change if done post-v1. Performance optimization is not in scope as long as it can be done post-v1, for example #6 , and none of the above introduce any significant degradation.

https://github.com/orgs/status-im/projects/54

**Comment by oskarth** [comment]
@cammellos this is great. Would you mind adding a super rough effort estimate for the 10 tasks? One some granularity of days, so something like:

#4 2d
#10 4d
#12 1d

I understand it's hard to know, but it helps give a better overview in Wrike at least for people less familiar with the work. We can adjust as we go too

**Comment by oskarth** [comment]
Cheers

**Comment by cammellos** [comment]
Added estimation, I am not counting in QA time for now as that's a bit unpredictable, so that's just development time, and it's skewed towards unknowns , so the least we understand something and how to do it the longer the estimation, also this is just to get a feel on what's the effort rather than being strict deadlines

**Comment by adambabik** [comment]
Can we close this or there is anything else required for V1?

**Comment by cammellos** [comment]
Closing as this is all done
